<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="4223" started-at="2019-01-13T01:28:32Z" finished-at="2019-01-13T01:28:36Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="4223" started-at="2019-01-13T01:28:32Z" finished-at="2019-01-13T01:28:36Z">
      <class name="com.webappsecurity.tests.ViewAccountSummary">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.webappsecurity.tests.ViewAccountSummary@4b4523f8]" name="setUp" is-config="true" duration-ms="3791" started-at="2019-01-13T01:28:32Z" finished-at="2019-01-13T01:28:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="viewSummary()[pri:0, instance:com.webappsecurity.tests.ViewAccountSummary@4b4523f8]" name="viewSummary" duration-ms="287" started-at="2019-01-13T01:28:36Z" finished-at="2019-01-13T01:28:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Not in login page expected [ZeroLog in] but found [Zero - Log in]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Not in login page expected [ZeroLog in] but found [Zero - Log in]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.webappsecurity.pages.LoginPage.<init>(LoginPage.java:16)
at com.webappsecurity.tests.ViewAccountSummary.viewSummary(ViewAccountSummary.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- viewSummary -->
      </class> <!-- com.webappsecurity.tests.ViewAccountSummary -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
